"""sync_models

Revision ID: 4265ea0101fb
Revises: 7f4a5a7338ad
Create Date: 2026-08-23 20:54:29.654119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4265ea0101fb'
down_revision: Union[str, Sequence[str], None] = '7f4a5a7338ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_type', sa.String(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('classification_level', sa.Integer(), nullable=False))
    op.drop_index('idx_gin_search', table_name='documents', postgresql_using='gin')
    op.alter_column('documents', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('users', sa.Column('clearance_level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'clearance_level')
    op.alter_column('documents', 'search_vector',
               existing_type=sa.Text(),
               type_=postgresql.TSVECTOR(),
               existing_nullable=True)
    op.create_index('idx_gin_search', 'documents', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_column('documents', 'classification_level')
    op.drop_table('document_permissions')
    # ### end Alembic commands ###
