"""Add workflow and integrity columns

Revision ID: 8f8844c5967c
Revises: 4265ea0101fb
Create Date: 2026-08-23 21:15:04.912376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f8844c5967c'
down_revision: Union[str, Sequence[str], None] = '4265ea0101fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('is_tampered', sa.Boolean(), nullable=True))
    op.drop_column('document_versions', 'created_at')
    op.add_column('documents', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('failure_reason', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('retry_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'retry_count')
    op.drop_column('documents', 'failure_reason')
    op.drop_column('documents', 'rejection_reason')
    op.add_column('document_versions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('document_versions', 'is_tampered')
    # ### end Alembic commands ###
