"""Add ApprovalRequest and Notification models

Revision ID: 941751cfff7f
Revises: ef8d27f25aa5
Create Date: 2026-08-24 14:12:44.896746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941751cfff7f'
down_revision: Union[str, Sequence[str], None] = 'ef8d27f25aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_search_vector'), table_name='documents', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_search_vector'), 'documents', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
