"""add_created_at_to_document_versions

Revision ID: ef8d27f25aa5
Revises: f0e4673ab06c
Create Date: 2026-08-24 00:07:17.987900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8d27f25aa5'
down_revision: Union[str, Sequence[str], None] = 'f0e4673ab06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_versions', 'created_at')
    # ### end Alembic commands ###
