"""add_historical_user_identity

Revision ID: f0e4673ab06c
Revises: e16383db42b5
Create Date: 2026-08-23 23:13:06.986516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e4673ab06c'
down_revision: Union[str, Sequence[str], None] = 'e16383db42b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preserved_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    
    # Custom logic to populate public_id and default is_deleted
    op.execute("UPDATE users SET is_deleted = false")
    op.execute("UPDATE users SET public_id = 'USR-' || upper(substr(md5(random()::text), 1, 8)) WHERE public_id IS NULL")
    
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'preserved_email')
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###
